# ----
# Site

title: Athenry Community Playground
url: "https://erinsweater.github.io"
baseurl: ""
google_analytics_key:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /icon.png
description: Fundraising and informational page for Athenry Community Plaground.
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Cause Template
  links:
    - https://github.com/CloudCannon/cause-jekyll-template

# -----
# Build

timezone: Etc/UTC

collections:
  staff_members:
    _icon: account_circle
    _hide_content: true
    _options:
      image:
        width: 250
        height: 250

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1880
          height: 1880
          uploads_dir: "/images/posts/"
  -
    scope:
      path: ""
    values:
      layout: "default"

donation_embed: '<script src="https://donorbox.org/widget.js" paypalExpress="false"></script><iframe src="https://donorbox.org/embed/athenry-community-playground?language=en" name="donorbox" allowpaymentrequest="allowpaymentrequest" seamless="seamless" frameborder="0" scrolling="no" height="900px" width="100%" style="max-width: 400px; max-width:auto; min-width: 250px; max-height:none!important" allow="payment"></iframe>'
newsletter_action: 

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock

# -----------
# CloudCannon

_options:
  header_background_image:
    width: 1880
    height: 1880
  newsletter_background_image:
    width: 1880
    height: 1880
