publish_mode: editorial_workflow
backend:
  name: github
  branch: main
  repo: athenry-playground/playground-website
media_folder: "jekyll_files/images"
public_folder: "/images"
collections:
- name: "event"
  label: "Event"
  folder: "jekyll_files/_events"
  create: true
  slug: "{{year}}-{{slug}}"
  fields:
    - { label: "Title", name: "title", widget: "string" }
    - { label: "Header image", name: "header_image", widget: "image" }
    - { label: "Start time", name: "start_time", widget: "datetime" }
    - { label: "Location", name: "location", widget: "string" }
    - { label: "Register URL", name: "register_url", widget: "text" }
    - { label: "Button text", name: "button_text", widget: "string" }
    - { label: "Body", name: "body", widget: "markdown" }
- name: "page"
  label: "Page"
  files:
    - file: "jekyll_files/index.html"
      label: "Home"
      name: "home"
      fields:
        - { label: "Title", name: "title", widget: "string" }
        - { label: "Latest Newsletter URL", name: "latest_newsletter_url", widget: "string" }
